### ISSUE TITLE
API endpoints proposal

### ISSUE THREAD

**Issue by gmltA** [MikhailSkirukha/bsuirfind#8]
**[admin]** `GET /users/:id` - get specific user by ID
**[admin]** `PUT /users/:id` - update specific user by ID

`/teams/captain/save` should be replaced with
**[user]** `PUT /user` or `PUT /users/:id` with security check to update only current account data

**[admin]** `GET /teams/:id` - get specific team by ID
**[admin]** `PUT /teams/:id` - update specific team by ID
**[admin]** `GET /teams/allForUser/:userId` - get all teams (including inactive \ former) for user

to be continued

**Comment by gmltA** [comment]
Let's proceed

**[admin]** `GET /teams` - get all teams DTO's (with full data)

**Comment by MikhailSkirukha** [comment]
@gmltA 
what team information do you wish to get by teams/id and teams/allforuser/userid? I need to know it to avoid extra "join" querries in my services.

**Comment by MikhailSkirukha** [comment]
@gmltA

> [admin] GET /users/:id - get specific user by ID
> [admin] PUT /users/:id - update specific user by ID
> 
> /teams/captain/save should be replaced with
> [user] PUT /user or PUT /users/:id with security check to update only current account data
> 
> [admin] GET /teams/:id - get specific team by ID
> [admin] PUT /teams/:id - update specific team by ID
> [admin] GET /teams/allForUser/:userId - get all teams (including inactive \ former) for user
> [admin] GET /teams - get all teams DTO's (with full data)

**DONE**
